### ISSUE TITLE
Foreign fonts render incorrectly

### ISSUE THREAD

**Issue by alexborisov** [mcwebb/angular-countrycodes#1]
Foreign fonts break for me. They read fine in my editor, but logging the output of `CountryCodes.getList()` returns garbled strings. Am I doing something wrong? Am i supposed to configure angular somehow?

**Comment by mcwebb** [comment]
Hi @alexborisov, I suspect the issue is due to encoding.
The file including all non-latin characters (e.g. the Chinese characters and Arabic script) is encoded in UTF-8, the names won't display properly if your app is displaying in a different encoding.
Try adding `<meta charset="utf-8" />` to the `<head />` of your page, or temporarily forcing UTF-8 in the browser.
